### ISSUE TITLE
Misleading and unhelpful error message

### ISSUE THREAD

**Issue by jetstream0** [BananoCoin/bananojs#18]
When trying to get the balance, occasionally this error is returned: `The server's account info cannot be retrieved, please try again.`
While its not exactly wrong, it makes it sound like the rpc node is offline or the request could not be made, when the problem could be that the account is unopened.
I encountered this specifically when trying to change represenative. The docs do not say you have to open the account before changing reps. 
If the above is not my misunderstanding, I can submit a pr to fix this

**Comment by coranos** [comment]
It's not misleading at all. The call to the node to ask for account_info returns undefined.

There is no way for me to determine the reason it returns undefined, or if it is undefined intermittently or permanently.

https://github.com/BananoCoin/bananojs/blob/caddc86f40b8364e19fb59bdc4e2075d2693c97c/app/scripts/banano-util.js#L817

https://github.com/BananoCoin/bananojs/blob/caddc86f40b8364e19fb59bdc4e2075d2693c97c/app/scripts/banano-util.js#L974
