### ISSUE TITLE
Typescript support.

### ISSUE THREAD

**Issue by ludwignagelhus** [BananoCoin/bananojs#25]
I am trying to make use of this in a typescript project, but I am having trouble making it work.

Typescript compiler tells me to create a "d.ts" file with `decare module "@bananocoin/bananojs";`, but I cannot make it work.

**Comment by coranos** [comment]
I've never used typescript, so I'm not sure how to help you.

are you using it inside nodejs? If so, i can try making a small example module.

**Comment by ludwignagelhus** [comment]
I have added my small testing project to the below linked repo

https://github.com/ludwignagelhus/test_banano_ts

**Comment by coranos** [comment]
should be fixed by the below pr

https://github.com/ludwignagelhus/test_banano_ts/pull/1
