### ISSUE TITLE
Lots of missing function documentation

### ISSUE THREAD

**Issue by Randomblock1** [BananoCoin/bananojs#31]
Lots of functions (especially in `app/scripts` do not have any JSDoc strings at all.

This is a big deal because:

 1. the README claims that ALL functions are documented: "complete documentation of all functions". 
 2. the CLI uses a lot of functions that are not in the documentation (for example, `bananoUtil.sendFromPrivateKey`, which is _very_ useful to have.)
 3. TypeScript automatic definition generation really really needs accurate documentation, and the PR I opened generates TypeScript definitions from the documentation. (Once I'm done with my current Booster project I'd like to convert this to TypeScript.)

Oh, and the `@memberof` tag should be lowercase and not uppercase, because we don't call them in the code uppercase. For example `BananoUtil` needs to become `bananoUtil`.

**Comment by coranos** [comment]
I updated the readme to say "complete documentation of all functions that are documented".

Internal methods are not completely documented. as you should be using the exposed, documented functions.

If you want to use sendFromPrivateKey use the external function sendAmountToBananoAccountWithRepresentativeAndPrevious 
https://github.com/BananoCoin/bananojs/blob/master/index.js#L195

I'll take a look at the typescript PR.

**Comment by coranos** [comment]
fixed existing documentation, so it generates the typescript bindings. try @bananocoin/bananojs@2.6.1.

if you have functions you want documented that aren't, feel free to document them.

**Comment by coranos** [comment]
i updated the docs, if you need something else specificly, just ask.
