### ISSUE TITLE
Why is bananode API URL defined for get private key methods?

### ISSUE THREAD

**Issue by kopeboy** [BananoCoin/bananojs#41]
Example from main.js:161
```js
commands['ngetprivatekey'] = async (seed, seedIx) => {
  const config = configs.nano;
  bananodeApi.setUrl(config.bananodeUrl);
  const privateKey = bananoUtil.getPrivateKey(seed, seedIx);
  console.log('nano getprivatekey privateKey', privateKey);
};
```
If you comment the third line here everything seems to work the same. I was even worried: why would we need an API when generating private keys? Are they being sent anywhere? 🙃 Isn't it better to remove that line to make people sleep better?

If I'm wrong, thank you for explanations 🙏🏻

**Comment by coranos** [comment]
fixed in 2.10.2. was a copy/paste error. seeds and private keys don't require the URL, but checking account balances do.
